#Users
mal = User.create(name: "Malcolm Reynolds")
kaylee = User.create(name: "Kaylee Frye")
zoe = User.create(name: "Zoe Washburne")
hoban = User.create(name: "Hoban 'Wash' Washburne")
inara = User.create(name: "Inara Serra")
jayne = User.create(name: "Jayne Cobb")
simon = User.create(name: "Simon Tam")
river = User.create(name: "River Tam")
derrial = User.create(name: "Derrial Book")

#Issues
Issue.create(name: "Spotted Reavers?", user_id: 1, open: true, private: false)
Issue.create(name: "Fix or replace parts?", user_id: 2, open: true, private: false)
Issue.create(name: "Abandon Saffron?", user_id: 1, open: true, private: false)
Issue.create(name: "New client?", user_id: 5, open: true, private: true)
Issue.create(name: "What to do with River", user_id: 1, open: true, private: false)
Issue.create(name: "Keep Atherton?", user_id: 5, open: true, private: true)
Issue.create(name: "Contact Parents?", user_id: 7, open: true, private: false)
Issue.create(name: "Have dealings with Patience", user_id: 1, open: true, private: false)

#Pros
Pros.create(description: "They might go by and leave us alone", issue_id: 1, weight: 3)
Pros.create(description: "They might not chase", issue_id: 2, weight: 5)
Pros.create(description: "Quick fix", issue_id: 3, weight: 4)
Pros.create(description: "Probably won't break again for a while", issue_id: 4, weight: 5)
Pros.create(description: "Gets rid of the crazy chick", issue_id: 5, weight: 4)
Pros.create(description: "More money", issue_id: 6, weight: 2)
Pros.create(description: "Might be a reward in it", issue_id: 7, weight: 3)
Pros.create(description: "Keeps us far away from the authorities", issue_id: 8, weight: 5)
Pros.create(description: "He pays well", issue_id: 9, weight: 1)
Pros.create(description: "They have money and could help hide her", issue_id: 10, weight: 3)
Pros.create(description: "They might turn her in", issue_id: 11, weight: 5)
Pros.create(description: "She can pay", issue_id: 12, weight: 5)

#Cons_doings
Cons.create(description: "They might come raid for spare parts", option_id: 1, weight: 4)
Cons.create(description: "They might chase on principle", option_id: 2, weight: 5)
Cons.create(description: "Might break again soon", option_id: 3, weight: 5)
Cons.create(description: "Costs money", option_id: 4, weight: 5)
Cons.create(description: "Moderately inhumane", option_id: 5, weight: 5)
Cons.create(description: "Might have to deal with an asshole", option_id: 6, weight: 4)
Cons.create(description: "Authorities might want to search ship", option_id: 7, weight: 4)
Cons.create(description: "Never know when she'll freak out", option_id: 8, weight: 3)
Cons.create(description: "He's an asshole", option_id: 9, weight: 5)
Cons.create(description: "They might turn her into authorities", option_id: 10, weight: 5)
Cons.create(description: "They're her parents too", option_id: 11, weight: 1)
Cons.create(description: "She shot Mal", option_id: 12, weight: 4)
