#Users
User.create(name: "Captain Picard", email: "picard@enterprise.com", password: "password")
User.create(name: "William Riker", email: "riker@enterprise.com", password: "password")
User.create(name: "Deanna Troi", email: "troi@enterprise.com", password: "password")
User.create(name: "Data", email: "data@enterprise.com", password: "password")
User.create(name: "Worf", email: "worf@enterprise.com", password: "password")
User.create(name: "Geordi La Forge", email: "laforge@enterprise.com", password: "password")
User.create(name: "Beverly Crusher", email: "crusher@enterprise.com", password: "password")
User.create(name: "Wesley Crusher", email: "wcrusher@enterprise.com", password: "password")
User.create(name: "Tasha Yar", email: "yar@enterprise.com", password: "password")

#Issues
Issue.create(name: "Engage Borg?", user_id: 1, open: true, private: false)
Issue.create(name: "Listen to Q?", user_id: 1, open: true, private: false)
Issue.create(name: "Keep the powers of Q?", user_id: 2, open: true, private: true)
Issue.create(name: "Visit a planet?", user_id: 8, private: false)
Issue.create(name: "Train on the holodeck?", user_id: 5, open: true, private: false)
Issue.create(name: "Engage the Romulans?", user_id: 1, open: true, private: false)
Issue.create(name: "Become more human?", user_id: 4, open: true, private: true)
Issue.create(name: "Go to Starfleet Academy?", user_id: 8, open: true, private: false)

#Pros
Pro.create(name: "We love a good fight", issue_id: 1, weight: 5)
Pro.create(name: "It's our duty to protect those who need it", issue_id: 1, weight: 4)
Pro.create(name: "He's an all-knowing 'higher' being", issue_id: 2, weight: 3)
Pro.create(name: "It's all-knowing, all-powerful", issue_id: 3, weight: 3)
Pro.create(name: "It's an opportunity to learn something new", issue_id: 4, weight: 5)
Pro.create(name: "The environment is infinitely adaptable", issue_id: 5, weight: 5)
Pro.create(name: "The computer is a greater challenge than other crew members", issue_id: 5, weight: 4)
Pro.create(name: "They are our enemies", issue_id: 6, weight: 4)
Pro.create(name: "It's what I was designed to do", issue_id: 7, weight: 5)
Pro.create(name: "I can learn a lot", issue_id: 8, weight: 4)
Pro.create(name: "It will jumpstart my career", issue_id: 8, weight: 5)

#Cons
Con.create(name: "The Borg are nearly unstoppable", issue_id: 1, weight: 4)
Con.create(name: "The Borg adapt quickly", issue_id: 1, weight: 3)
Con.create(name: "He's kind of an ass", issue_id: 2, weight: 4)
Con.create(name: "It means leaving my post on the Enterprise", issue_id: 3, weight: 4)
Con.create(name: "I have homework to do", issue_id: 4, weight: 2)
Con.create(name: "The Captain ordered me not to", issue_id: 4, weight: 5)
Con.create(name: "A computer cannot compete with a living being", issue_id: 5, weight: 4)
Con.create(name: "We are in the neutral zone", issue_id: 6, weight: 5)
Con.create(name: "It is difficult", issue_id: 7, weight: 2)
Con.create(name: "I'll be the youngest cadet there", issue_id: 8, weight: 3)
